### PR TITLE
Fix: Add Intro.js guided tour functionality and map integration

### PR DESCRIPTION
**Pull request by Lemeri123**
What does this PR do?
- Implements a guided tour using Intro.js to improve user onboarding.

### CODE REVIEW

**Comment by bacloud22** [comment]
Hi thank you @Lemeri123 
I will test it and merge as soon as I can. No worries. 

Thank you

**Comment by bacloud22** [comment]
Please make use of :
`messages.tour` in *./libs/services/messages.js*

Thank you

**Review by Lemeri123 — COMMENTED** [review]
cc
@bacloud22

**Comment by bacloud22** [comment]
Thank you @Lemeri123

**Pull request merged**
