### PR TITLE
I optimized weather data caching with city-by-city storage

### PR DESCRIPTION
**Pull request by Lemeri123**
This update enhances the caching mechanism for weather data by implementing city-by-city caching.  #11

### CODE REVIEW

**Comment by Lemeri123** [comment]
@bacloud22 please check this out!!!!

**Comment by bacloud22** [comment]
@Lemeri123 please rebase. thank you !!

**Comment by Lemeri123** [comment]
Thank you @bacloud22

**Comment by Lemeri123** [comment]
Thank you @bacloud22

**Comment by bacloud22** [comment]
Hi @Lemeri123 I already fixed your merge, and even more.
Please do not use ChatGPT without testing. It still does not work for some reason. please check

**Comment by bacloud22** [comment]
pull my last commit and recheck please.

**Pull request merged**
