### PR TITLE
Fixed Cypress UI tests

### PR DESCRIPTION
**Pull request by Lemeri123**
cc.
@bacloud22

### CODE REVIEW

**Comment by Lemeri123** [comment]
@bacloud22. Please review this and let me know because this was one confusing one

**Comment by bacloud22** [comment]
Hi @Lemeri123 Thank you for your contributions.
Actually, your modifications are fine, I did not test them,
but actual Cypress recipes are here : https://github.com/bacloud22/WeatherVenue/tree/main/cypress

This file is the one that enables Github actions to run Cypress tests. What you need to do is to activate actions on your fork settings, and push commits and see if tests run successfully.

**Comment by Lemeri123** [comment]
Am on it. but I cant quite figure out whats not right. let me keep trying thou

**Review by bacloud22 — APPROVED** [review]

**Comment by bacloud22** [comment]
Hi @Lemeri123 
Action does not run on my repo. Does it run on your repo ? Probably it has to do with my GitHub configurations. Thank you anyway

**Comment by bacloud22** [comment]
Probably merge commit on action itself doesn't trigger the action itself. Probably we'll see on next commit on source

**Comment by Lemeri123** [comment]
@bacloud22, it did run on my repo but after a series of trial and tests. I still think I need to make further changes for it might still have some areas to deal with. Am still looking at it

**Comment by Lemeri123** [comment]
Let me continue seeing if there is any area to be changed. If there is then I'll open another pull request. And if there is anything you want me to edit then you can as well let me know!!!

**Pull request merged**
